when:
  - event: pull_request
    branch: trunk

steps:
  - name: build
    image: docker.io/theoparis/chimera
    commands:
      - apk add cmake ninja clang doctest pkgconf linux-headers
      - cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
      - cmake --build build
      - ctest --test-dir build --output-on-failure
