name: build

on:
  pull_request:
  merge_group:

jobs:
  test:
    runs-on:
    steps:
      - uses: actions/checkout@v4
      - name: work around ASLR+ASAN compatibility
        run: sudo sysctl -w vm.mmap_rnd_bits=28
      - name: Build docker images
        run: docker build -t ci -f tools/ci/Dockerfile
      - name: Run tests
        run: docker run --rm -v ${{ github.workspace }}:/src -w /src ci tools/ci/build.sh
